name = "Vista Companion"
author = "Houdeeny"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff806d5a89017efd7fc75b91403b779cffd6f5456e733ee8bc94a00916d75346"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
