name = "Vista Companion"
author = "Houdeeny"
version = "1.21.4-1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d54e136be1db11cb4ad5336c5dbeb68840cebca506eeb02a893fe83f7b5a88d"

[versions]
fabric = "0.16.13"
minecraft = "1.21.4"
