name = "Vista Companion"
author = "Houdeeny"
version = "0.0.1-alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ecf84c97cbd8cac786f39c8f252889af675eb3c93ceb7f8d6c9e01b69958193b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
