name = "Vista Companion"
author = "Houdeeny"
version = "1.21.4-1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c237fa2edd74b5b305c21e714acad4543aac96be895dc3da7e1903f8189be56a"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
