name = "Vista Companion"
author = "Houdeeny"
version = "1.21.4-1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1ae1e172766cf33b0a13b5f33468357a15539950b1a393301596dad807d69b6"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
