name = "Vista Companion"
author = "Houdeeny"
version = "1.21.4-1.0.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9775cb980aa264b183eb14d980571b98feedec3b65c00303c82fd9f92dfe0216"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
