name = "Vista Companion"
author = "Houdeeny"
version = "1.21.4-1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "677c9780976700d7243038ba98afacfbafad13ed51bd9079ef997c5051a7cbca"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
